export const NAME_FILTER_CHANGE = 'NAME_FILTER_CHANGE';
export const CUISINE_FILTER_CHANGE = 'CUISINE_FILTER_CHANGE';
export const RATING_FILTER_CHANGE = 'RATING_FILTER_CHANGE';
export const DELIVERY_FILTER_CHANGE = 'DELIVERY_FILTER_CHANGE';
