export const NAME_FILTER_CHANGE = 'NAME_FILTER_CHANGE';
export const CUISINE_FILTER_CHANGE = 'CUISINE_FILTER_CHANGE';
export const RATING_FILTER_CHANGE = 'RATING_FILTER_CHANGE';
export const DELIVERY_FILTER_CHANGE = 'DELIVERY_FILTER_CHANGE';

export const SET_RESTAURANTS = 'SET_RESTAURANTS';
export const FETCH_RESTAURANTS_FAILED = 'FETCH_RESTAURANTS_FAILED';

export const SET_CUISINES = 'SET_CUISINES';
export const FETCH_CUISINES_FAILED = 'FETCH_CUISINES_FAILED';
